# environment setting
data_path: ./

# dataset config
field_separator: "\t" 
USER_ID_FIELD: userid
ITEM_ID_FIELD: tmdb_id
RATING_FIELD: rating
load_col:
  inter: [userid, tmdb_id, rating]

# model config
embedding_size: 128

# Training and evaluation config
epochs: 50
train_batch_size: 256
eval_batch_size: 256
learning_rate: 0.001
neg_sampling:
    {'uniform': 1, 'dynamic': 1}
stopping_step: 10
eval_args:
    group_by: user
    order: RO
    split: {'RS': [0.8,0.1,0.1]}
    mode: full
metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk: 20
valid_metric: NDCG@20
metric_decimal_place: 4
